# Generated by Django 3.1.1 on 2020-12-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'articolo', 'verbose_name_plural': 'articoli'},
        ),
        migrations.AlterModelOptions(
            name='giornalista',
            options={'verbose_name': 'giornalista', 'verbose_name_plural': 'giornalisti'},
        ),
    ]
